### ISSUE TITLE
parking lot based backend

### ISSUE THREAD

**Issue by matklad** [niklasf/double-checked-cell#1]
It might be fun to add `parking_lot` as an **optional** dependency as an alternative impl of Mutex: it claims to be smaller & faster then std versions.

**Comment by niklasf** [comment]
That's an intresting prospect and might allow making DoubleCheckedCell::new const.

Will require some care to properly handle panics. Currently it's easy, because the Mutex from std will just be poisoned forever.

I expect the impact on performance to be minimal for most use cases, since the mutex is no longer used after the cell is initialized. Probably it would be a good idea to add a benchmark anyway.

**Comment by niklasf** [comment]
`double_checked_cell` 2.0.0 will have two new optional features: `parking_lot_mutex` and `const_fn` (which also implies the former).
