### ISSUE TITLE
One cell to rule them all

### ISSUE THREAD

**Issue by matklad** [niklasf/double-checked-cell#2]
cc @indiv0, @khuey

Looks like we've got a bunch of crates which provide similar but not quite identical functionality. 

I wonder if we should try to unify API and provide a single crate with all various flavors of cells? 

Just recently I've rolled my own flavor of [`LazyTranform`](https://github.com/rust-analyzer/rowan/blob/9622bf74103a7c3b02c738d4c706ecbbd93e4c5b/src/swap_cell.rs) just because it was hard to find among the lazy crates I knew about :) 

The main question is "does a unifying API exist at all?". I hope it is! Here are my rough thoughts:

* I like the `sync/unsync` factoring of `once_cell`.
* `LazyTransform` is a strictly more powerful primitive than `OnceCell` (Though, I'd love to have "Once" in the name). I think we can build `double_checked_cell` flavor (with failable initialization), if we require the failure to return both the error and original value: `get_or_init(f: FnOnce(U) -> Result<T, (U, E)>)`
* The difference in API between once_cell and double_checked_cell is that one has faillable initialization while the other doesn't. Of course it's better to have more powerful API! But is there any difference in memory or time overhead between using a `Once` and using a `Mutex` (I think we should care only about parking_lot case here).

**Comment by matklad** [comment]
The secret plan here is of course to build a now-stable const-fn based `Lazy` and to overthrow the `lazy_static` ;-)

**Comment by niklasf** [comment]
In the presence of panics it looks like `f: FnOnce(U) -> Result<T, (U, E)>` will run into the [take_mut](https://docs.rs/take_mut/0.2.2/take_mut/index.html) problem, which can get a bit ugly.

Maybe `U: Clone` is reasonable for fallible initilization? I currently use `(U, DoubleCheckedCell<T>)` instead of `LazyTransform<U, T>` and the bound definitely seems to hold for all use-cases I can think of.

If that is solved in one way or another then all the existing APIs can be easily built on top of that in safe code.

(Not just yet overthrowing `lazy_static` with `parking_lot` and `min_const_fn` though:)

```
error: trait bounds other than `Sized` on const fn parameters are unstable
  --> lock_api/src/mutex.rs:99:6
   |
99 | impl<R: RawMutex, T> Mutex<R, T> {
   |      ^
```

**Comment by matklad** [comment]
>In the presence of panics it looks like f: FnOnce(U) -> Result<T, (U, E)> will run into the take_mut problem, which can get a bit ugly.

I think this can be handled by poisoning, which we get for free if we use std's Mutex.

>Maybe U: Clone is reasonable for fallible initilization?

That I think equivalent to just passing an `&U` to the initializing function, and it kinda defeats the purpose of LazyTransform: using the same memory for both `T` and `U`.

**Comment by niklasf** [comment]
Congrats on once_cell 0.2, released a while ago. I think we can close this issue.
